function [ TRANSM ] = Func_fkine(InitDEG,a1,a2,d4,d6)
%   InitDEG 关节变量
%   a1,a2,d4,d6  杆件参数
%求解正运动学方程
theta1 = InitDEG(1)*pi/180;  
theta2 = InitDEG(2)*pi/180;
theta3 = InitDEG(3)*pi/180;
theta4 = InitDEG(4)*pi/180;
theta5 = InitDEG(5)*pi/180;
theta6 = InitDEG(6)*pi/180;

TRANSM =[ 
  cos(theta4)*sin(theta1)*sin(theta6) + cos(theta5)*cos(theta6)*sin(theta1)*sin(theta4) - cos(theta1)*cos(theta2)*cos(theta3)*sin(theta4)*sin(theta6) - cos(theta1)*cos(theta2)*cos(theta6)*sin(theta3)*sin(theta5) - cos(theta1)*cos(theta3)*cos(theta6)*sin(theta2)*sin(theta5) + cos(theta1)*sin(theta2)*sin(theta3)*sin(theta4)*sin(theta6) + cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6) - cos(theta1)*cos(theta4)*cos(theta5)*cos(theta6)*sin(theta2)*sin(theta3), cos(theta4)*cos(theta6)*sin(theta1) - cos(theta5)*sin(theta1)*sin(theta4)*sin(theta6) - cos(theta1)*cos(theta2)*cos(theta3)*cos(theta6)*sin(theta4) + cos(theta1)*cos(theta6)*sin(theta2)*sin(theta3)*sin(theta4) + cos(theta1)*cos(theta2)*sin(theta3)*sin(theta5)*sin(theta6) + cos(theta1)*cos(theta3)*sin(theta2)*sin(theta5)*sin(theta6) - cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*sin(theta6) + cos(theta1)*cos(theta4)*cos(theta5)*sin(theta2)*sin(theta3)*sin(theta6), sin(theta1)*sin(theta4)*sin(theta5) + cos(theta1)*cos(theta2)*cos(theta5)*sin(theta3) + cos(theta1)*cos(theta3)*cos(theta5)*sin(theta2) + cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*sin(theta5) - cos(theta1)*cos(theta4)*sin(theta2)*sin(theta3)*sin(theta5), a1*cos(theta1) + a2*cos(theta1)*cos(theta2) + d4*cos(theta1)*cos(theta2)*sin(theta3) + d4*cos(theta1)*cos(theta3)*sin(theta2) + d6*sin(theta1)*sin(theta4)*sin(theta5) + d6*cos(theta1)*cos(theta2)*cos(theta5)*sin(theta3) + d6*cos(theta1)*cos(theta3)*cos(theta5)*sin(theta2) + d6*cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*sin(theta5) - d6*cos(theta1)*cos(theta4)*sin(theta2)*sin(theta3)*sin(theta5);
  sin(theta1)*sin(theta2)*sin(theta3)*sin(theta4)*sin(theta6) - cos(theta1)*cos(theta5)*cos(theta6)*sin(theta4) - cos(theta2)*cos(theta3)*sin(theta1)*sin(theta4)*sin(theta6) - cos(theta2)*cos(theta6)*sin(theta1)*sin(theta3)*sin(theta5) - cos(theta3)*cos(theta6)*sin(theta1)*sin(theta2)*sin(theta5) - cos(theta1)*cos(theta4)*sin(theta6) + cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6)*sin(theta1) - cos(theta4)*cos(theta5)*cos(theta6)*sin(theta1)*sin(theta2)*sin(theta3), cos(theta1)*cos(theta5)*sin(theta4)*sin(theta6) - cos(theta1)*cos(theta4)*cos(theta6) - cos(theta2)*cos(theta3)*cos(theta6)*sin(theta1)*sin(theta4) + cos(theta6)*sin(theta1)*sin(theta2)*sin(theta3)*sin(theta4) + cos(theta2)*sin(theta1)*sin(theta3)*sin(theta5)*sin(theta6) + cos(theta3)*sin(theta1)*sin(theta2)*sin(theta5)*sin(theta6) - cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*sin(theta1)*sin(theta6) + cos(theta4)*cos(theta5)*sin(theta1)*sin(theta2)*sin(theta3)*sin(theta6), cos(theta2)*cos(theta5)*sin(theta1)*sin(theta3) - cos(theta1)*sin(theta4)*sin(theta5) + cos(theta3)*cos(theta5)*sin(theta1)*sin(theta2) + cos(theta2)*cos(theta3)*cos(theta4)*sin(theta1)*sin(theta5) - cos(theta4)*sin(theta1)*sin(theta2)*sin(theta3)*sin(theta5), a1*sin(theta1) + a2*cos(theta2)*sin(theta1) + d4*cos(theta2)*sin(theta1)*sin(theta3) + d4*cos(theta3)*sin(theta1)*sin(theta2) - d6*cos(theta1)*sin(theta4)*sin(theta5) + d6*cos(theta2)*cos(theta5)*sin(theta1)*sin(theta3) + d6*cos(theta3)*cos(theta5)*sin(theta1)*sin(theta2) + d6*cos(theta2)*cos(theta3)*cos(theta4)*sin(theta1)*sin(theta5) - d6*cos(theta4)*sin(theta1)*sin(theta2)*sin(theta3)*sin(theta5);
                                                                                                                                                                  cos(theta2)*cos(theta3)*cos(theta6)*sin(theta5) - cos(theta2)*sin(theta3)*sin(theta4)*sin(theta6) - cos(theta3)*sin(theta2)*sin(theta4)*sin(theta6) - cos(theta6)*sin(theta2)*sin(theta3)*sin(theta5) + cos(theta2)*cos(theta4)*cos(theta5)*cos(theta6)*sin(theta3) + cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6)*sin(theta2),                                                                                                                                                                 sin(theta2)*sin(theta3)*sin(theta5)*sin(theta6) - cos(theta3)*cos(theta6)*sin(theta2)*sin(theta4) - cos(theta2)*cos(theta3)*sin(theta5)*sin(theta6) - cos(theta2)*cos(theta6)*sin(theta3)*sin(theta4) - cos(theta2)*cos(theta4)*cos(theta5)*sin(theta3)*sin(theta6) - cos(theta3)*cos(theta4)*cos(theta5)*sin(theta2)*sin(theta6),                                                                                       cos(theta5)*sin(theta2)*sin(theta3) - cos(theta2)*cos(theta3)*cos(theta5) + cos(theta2)*cos(theta4)*sin(theta3)*sin(theta5) + cos(theta3)*cos(theta4)*sin(theta2)*sin(theta5),                                                                                                                                               a2*sin(theta2) - d4*cos(theta2)*cos(theta3) + d4*sin(theta2)*sin(theta3) - d6*cos(theta2)*cos(theta3)*cos(theta5) + d6*cos(theta5)*sin(theta2)*sin(theta3) + d6*cos(theta2)*cos(theta4)*sin(theta3)*sin(theta5) + d6*cos(theta3)*cos(theta4)*sin(theta2)*sin(theta5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                                                                                                                                  1
        ];

end

